package com.deep.two.model.query.basic;

import com.deep.two.dao.util.Operator;
import com.deep.two.model.query.QueryModel;

// Generated 2016-8-31 21:36:25 by Hibernate Tools 3.4.0.CR1

/**
 * BasicProvinceArea generated by hbm2java
 */
public class BasicProvinceAreaQueryModel extends QueryModel {

	private String province;
	private String provinceOperator = Operator.IN;
	private String area;
	private String areaOperator = Operator.IN;
	private String hot;
	private String hotOperator = Operator.IN;

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getProvinceOperator() {
		return this.provinceOperator;
	}

	public void setProvinceOperator(String provinceOperator) {
		this.provinceOperator = provinceOperator;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getAreaOperator() {
		return this.areaOperator;
	}

	public void setAreaOperator(String areaOperator) {
		this.areaOperator = areaOperator;
	}

	public String getHot() {
		return this.hot;
	}

	public void setHot(String hot) {
		this.hot = hot;
	}

	public String getHotOperator() {
		return this.hotOperator;
	}

	public void setHotOperator(String hotOperator) {
		this.hotOperator = hotOperator;
	}

}
