package com.deep.two.model.query.basic;

import com.deep.two.dao.util.Operator;
import com.deep.two.model.query.QueryModel;

// Generated 2016-8-31 21:36:25 by Hibernate Tools 3.4.0.CR1

/**
 * BasicResearchField generated by hbm2java
 */
public class BasicResearchFieldQueryModel extends QueryModel {
	private String name;
	private String nameOperator = Operator.IN;

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNameOperator() {
		return this.nameOperator;
	}

	public void setNameOperator(String nameOperator) {
		this.nameOperator = nameOperator;
	}
}
