package com.deep.two.model.query.basic;

import com.deep.two.model.query.QueryModel;

// Generated 2016-8-31 21:36:25 by Hibernate Tools 3.4.0.CR1

/**
 * BasicArea generated by hbm2java
 */
public class BasicAreaQueryModel extends QueryModel {

}
