package com.deep.two.authority.model;

// Generated 2015-7-3 15:54:57 by Hibernate Tools 3.4.0.CR1

/**
 * CpubTResource generated by hbm2java
 */
public class ResourceModel {

	private String id;
	private String resourceName;
	private String resourceDesc;
	private String resourceType;
	private String resourceStr;

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getResourceName() {
        return this.resourceName;
    }

    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }

    public String getResourceDesc() {
        return this.resourceDesc;
    }

    public void setResourceDesc(String resourceDesc) {
        this.resourceDesc = resourceDesc;
    }

    public String getResourceType() {
        return this.resourceType;
    }

    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }

	public String getResourceStr() {
		return this.resourceStr;
	}

	public void setResourceStr(String resourceStr) {
		this.resourceStr = resourceStr;
	}

}
