package com.deep.two.authority.model;

// Generated 2015-7-3 15:54:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CpubTRole generated by hbm2java
 */
public class RoleModel {

    private String id;
    private String roleName;
    private String roleDesc;
    private Set<ResourceModel> resourceModels = new HashSet<ResourceModel>(0);

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getRoleDesc() {
        return roleDesc;
    }

    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc;
    }

	public Set<ResourceModel> getResourceModels() {
		return resourceModels;
	}

	public void setResourceModels(Set<ResourceModel> resourceModels) {
		this.resourceModels = resourceModels;
	}
}
