package com.deep.two.authority.model;

// Generated 2015-7-3 15:54:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CpubTUser generated by hbm2java
 */
public class UserModel {

	private String id;
	private String username;
	private String password;
	private String validateCode;
	private String email;
	private String telno;
	private String userType;
	private Date whenCreate;
	private Date whenLastUpdate;
	private Date whenLastLogin;
	private String status;
	private String communicateStatus;
	private String remark;
	private String removeFlag;
    private Set<RoleModel> roleModels = new HashSet<RoleModel>(0);

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getTelno() {
        return telno;
    }

    public void setTelno(String telno) {
        this.telno = telno;
    }

    public String getUserType() {
        return userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }

    public Date getWhenCreate() {
        return whenCreate;
    }

    public void setWhenCreate(Date whenCreate) {
        this.whenCreate = whenCreate;
    }

    public Date getWhenLastUpdate() {
        return whenLastUpdate;
    }

    public void setWhenLastUpdate(Date whenLastUpdate) {
        this.whenLastUpdate = whenLastUpdate;
    }

    public Date getWhenLastLogin() {
        return whenLastLogin;
    }

    public void setWhenLastLogin(Date whenLastLogin) {
        this.whenLastLogin = whenLastLogin;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getCommunicateStatus() {
        return communicateStatus;
    }

    public void setCommunicateStatus(String communicateStatus) {
        this.communicateStatus = communicateStatus;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Set<RoleModel> getRoleModels() {
        return roleModels;
    }

    public void setRoleModels(Set<RoleModel> roleModels) {
        this.roleModels = roleModels;
    }

	public String getValidateCode() {
		return this.validateCode;
	}

	public void setValidateCode(String validateCode) {
		this.validateCode = validateCode;
	}

	public String getRemoveFlag() {
		return this.removeFlag;
	}

	public void setRemoveFlag(String removeFlag) {
		this.removeFlag = removeFlag;
	}
}
