package com.deep.two.service.basic;

import com.deep.two.orm.BasicResearchField;
import com.deep.two.service.BaseService;

/**
 * BasicResearchField generated by hbm2java
 */
public interface BasicResearchFieldService extends BaseService<BasicResearchField> {
	
}