package com.deep.two.dao.basic;

import org.springframework.stereotype.Repository;
import com.deep.two.dao.AbstractDAO;
import com.deep.two.orm.BasicProvinceArea;

// Generated 2016-8-31 21:36:25 by Hibernate Tools 3.4.0.CR1

/**
 * BasicProvinceArea generated by hbm2java
 */
@Repository
public class BasicProvinceAreaDAO extends AbstractDAO<BasicProvinceArea> {

	@Override
	public Class<BasicProvinceArea> getCurrentClass() {
		return BasicProvinceArea.class;
	}
}
