package com.deep.two.dao.basic;

import org.springframework.stereotype.Repository;
import com.deep.two.dao.AbstractDAO;
import com.deep.two.orm.BasicProvince;

// Generated 2016-8-31 21:36:25 by Hibernate Tools 3.4.0.CR1

/**
 * BasicProvince generated by hbm2java
 */
@Repository
public class BasicProvinceDAO extends AbstractDAO<BasicProvince> {

	@Override
	public Class<BasicProvince> getCurrentClass() {
		return BasicProvince.class;
	}
}
