package com.deep.two.orm;

// Generated 2016-12-27 21:27:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Achievement generated by hbm2java
 */
public class Achievement implements java.io.Serializable {

	private String id;
	private ResearchGroup researchGroup;
	private String logoUrl;
	private String name;
	private String domain;
	private String type;
	private String patent;
	private String patenter;
	private String amount;
	private String solution;
	private String phase;
	private String applyTo;
	private String expectedEffect;
	private Integer caseNum;
	private String caseDetail;
	private String cooperationType;
	private String attachUrl;
	private String sequenceNumber;
	private String status;
	private String communicateStatus;
	private String remark;
	private Integer concernNumber;
	private Integer scanNumber;
	private String seqNum;
	private String recommendFlag;
	private String whoLastUpdate;
	private Date whenCreate;
	private String whoCreate;
	private Date whenLastUpdate;
	private String removeFlag;
	private Set<AchievementFollower> achievementFollowers = new HashSet<AchievementFollower>(
			0);

	public Achievement() {
	}

	public Achievement(String id, String sequenceNumber) {
		this.id = id;
		this.sequenceNumber = sequenceNumber;
	}

	public Achievement(String id, ResearchGroup researchGroup, String logoUrl,
			String name, String domain, String type, String patent,
			String patenter, String amount, String solution, String phase,
			String applyTo, String expectedEffect, Integer caseNum,
			String caseDetail, String cooperationType, String attachUrl,
			String sequenceNumber, String status, String communicateStatus,
			String remark, Integer concernNumber, Integer scanNumber,
			String seqNum, String recommendFlag, String whoLastUpdate,
			Date whenCreate, String whoCreate, Date whenLastUpdate,
			String removeFlag, Set<AchievementFollower> achievementFollowers) {
		this.id = id;
		this.researchGroup = researchGroup;
		this.logoUrl = logoUrl;
		this.name = name;
		this.domain = domain;
		this.type = type;
		this.patent = patent;
		this.patenter = patenter;
		this.amount = amount;
		this.solution = solution;
		this.phase = phase;
		this.applyTo = applyTo;
		this.expectedEffect = expectedEffect;
		this.caseNum = caseNum;
		this.caseDetail = caseDetail;
		this.cooperationType = cooperationType;
		this.attachUrl = attachUrl;
		this.sequenceNumber = sequenceNumber;
		this.status = status;
		this.communicateStatus = communicateStatus;
		this.remark = remark;
		this.concernNumber = concernNumber;
		this.scanNumber = scanNumber;
		this.seqNum = seqNum;
		this.recommendFlag = recommendFlag;
		this.whoLastUpdate = whoLastUpdate;
		this.whenCreate = whenCreate;
		this.whoCreate = whoCreate;
		this.whenLastUpdate = whenLastUpdate;
		this.removeFlag = removeFlag;
		this.achievementFollowers = achievementFollowers;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public ResearchGroup getResearchGroup() {
		return this.researchGroup;
	}

	public void setResearchGroup(ResearchGroup researchGroup) {
		this.researchGroup = researchGroup;
	}

	public String getLogoUrl() {
		return this.logoUrl;
	}

	public void setLogoUrl(String logoUrl) {
		this.logoUrl = logoUrl;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getPatent() {
		return this.patent;
	}

	public void setPatent(String patent) {
		this.patent = patent;
	}

	public String getPatenter() {
		return this.patenter;
	}

	public void setPatenter(String patenter) {
		this.patenter = patenter;
	}

	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	public String getSolution() {
		return this.solution;
	}

	public void setSolution(String solution) {
		this.solution = solution;
	}

	public String getPhase() {
		return this.phase;
	}

	public void setPhase(String phase) {
		this.phase = phase;
	}

	public String getApplyTo() {
		return this.applyTo;
	}

	public void setApplyTo(String applyTo) {
		this.applyTo = applyTo;
	}

	public String getExpectedEffect() {
		return this.expectedEffect;
	}

	public void setExpectedEffect(String expectedEffect) {
		this.expectedEffect = expectedEffect;
	}

	public Integer getCaseNum() {
		return this.caseNum;
	}

	public void setCaseNum(Integer caseNum) {
		this.caseNum = caseNum;
	}

	public String getCaseDetail() {
		return this.caseDetail;
	}

	public void setCaseDetail(String caseDetail) {
		this.caseDetail = caseDetail;
	}

	public String getCooperationType() {
		return this.cooperationType;
	}

	public void setCooperationType(String cooperationType) {
		this.cooperationType = cooperationType;
	}

	public String getAttachUrl() {
		return this.attachUrl;
	}

	public void setAttachUrl(String attachUrl) {
		this.attachUrl = attachUrl;
	}

	public String getSequenceNumber() {
		return this.sequenceNumber;
	}

	public void setSequenceNumber(String sequenceNumber) {
		this.sequenceNumber = sequenceNumber;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getCommunicateStatus() {
		return this.communicateStatus;
	}

	public void setCommunicateStatus(String communicateStatus) {
		this.communicateStatus = communicateStatus;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getConcernNumber() {
		return this.concernNumber;
	}

	public void setConcernNumber(Integer concernNumber) {
		this.concernNumber = concernNumber;
	}

	public Integer getScanNumber() {
		return this.scanNumber;
	}

	public void setScanNumber(Integer scanNumber) {
		this.scanNumber = scanNumber;
	}

	public String getSeqNum() {
		return this.seqNum;
	}

	public void setSeqNum(String seqNum) {
		this.seqNum = seqNum;
	}

	public String getRecommendFlag() {
		return this.recommendFlag;
	}

	public void setRecommendFlag(String recommendFlag) {
		this.recommendFlag = recommendFlag;
	}

	public String getWhoLastUpdate() {
		return this.whoLastUpdate;
	}

	public void setWhoLastUpdate(String whoLastUpdate) {
		this.whoLastUpdate = whoLastUpdate;
	}

	public Date getWhenCreate() {
		return this.whenCreate;
	}

	public void setWhenCreate(Date whenCreate) {
		this.whenCreate = whenCreate;
	}

	public String getWhoCreate() {
		return this.whoCreate;
	}

	public void setWhoCreate(String whoCreate) {
		this.whoCreate = whoCreate;
	}

	public Date getWhenLastUpdate() {
		return this.whenLastUpdate;
	}

	public void setWhenLastUpdate(Date whenLastUpdate) {
		this.whenLastUpdate = whenLastUpdate;
	}

	public String getRemoveFlag() {
		return this.removeFlag;
	}

	public void setRemoveFlag(String removeFlag) {
		this.removeFlag = removeFlag;
	}

	public Set<AchievementFollower> getAchievementFollowers() {
		return this.achievementFollowers;
	}

	public void setAchievementFollowers(
			Set<AchievementFollower> achievementFollowers) {
		this.achievementFollowers = achievementFollowers;
	}

}
