package com.deep.two.orm;

// Generated 2016-12-27 21:27:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FundRequirement generated by hbm2java
 */
public class FundRequirement implements java.io.Serializable {

	private String id;
	private CompanyUser companyUser;
	private String name;
	private String domain;
	private String contactName;
	private String contactTel;
	private String contactEmail;
	private String projectName;
	private String projectTeam;
	private String projectIntro;
	private String projectPhase;
	private String projectProspect;
	private String amountNeeded;
	private String attachUrl;
	private String sequenceNumber;
	private String status;
	private String communicateStatus;
	private String remark;
	private Integer concernNumber;
	private Integer scanNumber;
	private String seqNum;
	private String recommendFlag;
	private String logoUrl;
	private Date whenCreate;
	private String whoCreate;
	private Date whenLastUpdate;
	private String whoLastUpdate;
	private String removeFlag;
	private Set<FundRequirementFollower> fundRequirementFollowers = new HashSet<FundRequirementFollower>(
			0);

	public FundRequirement() {
	}

	public FundRequirement(String id, CompanyUser companyUser) {
		this.id = id;
		this.companyUser = companyUser;
	}

	public FundRequirement(String id, CompanyUser companyUser, String name,
			String domain, String contactName, String contactTel,
			String contactEmail, String projectName, String projectTeam,
			String projectIntro, String projectPhase, String projectProspect,
			String amountNeeded, String attachUrl, String sequenceNumber,
			String status, String communicateStatus, String remark,
			Integer concernNumber, Integer scanNumber, String seqNum,
			String recommendFlag, String logoUrl, Date whenCreate,
			String whoCreate, Date whenLastUpdate, String whoLastUpdate,
			String removeFlag,
			Set<FundRequirementFollower> fundRequirementFollowers) {
		this.id = id;
		this.companyUser = companyUser;
		this.name = name;
		this.domain = domain;
		this.contactName = contactName;
		this.contactTel = contactTel;
		this.contactEmail = contactEmail;
		this.projectName = projectName;
		this.projectTeam = projectTeam;
		this.projectIntro = projectIntro;
		this.projectPhase = projectPhase;
		this.projectProspect = projectProspect;
		this.amountNeeded = amountNeeded;
		this.attachUrl = attachUrl;
		this.sequenceNumber = sequenceNumber;
		this.status = status;
		this.communicateStatus = communicateStatus;
		this.remark = remark;
		this.concernNumber = concernNumber;
		this.scanNumber = scanNumber;
		this.seqNum = seqNum;
		this.recommendFlag = recommendFlag;
		this.logoUrl = logoUrl;
		this.whenCreate = whenCreate;
		this.whoCreate = whoCreate;
		this.whenLastUpdate = whenLastUpdate;
		this.whoLastUpdate = whoLastUpdate;
		this.removeFlag = removeFlag;
		this.fundRequirementFollowers = fundRequirementFollowers;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public CompanyUser getCompanyUser() {
		return this.companyUser;
	}

	public void setCompanyUser(CompanyUser companyUser) {
		this.companyUser = companyUser;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	public String getContactTel() {
		return this.contactTel;
	}

	public void setContactTel(String contactTel) {
		this.contactTel = contactTel;
	}

	public String getContactEmail() {
		return this.contactEmail;
	}

	public void setContactEmail(String contactEmail) {
		this.contactEmail = contactEmail;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getProjectTeam() {
		return this.projectTeam;
	}

	public void setProjectTeam(String projectTeam) {
		this.projectTeam = projectTeam;
	}

	public String getProjectIntro() {
		return this.projectIntro;
	}

	public void setProjectIntro(String projectIntro) {
		this.projectIntro = projectIntro;
	}

	public String getProjectPhase() {
		return this.projectPhase;
	}

	public void setProjectPhase(String projectPhase) {
		this.projectPhase = projectPhase;
	}

	public String getProjectProspect() {
		return this.projectProspect;
	}

	public void setProjectProspect(String projectProspect) {
		this.projectProspect = projectProspect;
	}

	public String getAmountNeeded() {
		return this.amountNeeded;
	}

	public void setAmountNeeded(String amountNeeded) {
		this.amountNeeded = amountNeeded;
	}

	public String getAttachUrl() {
		return this.attachUrl;
	}

	public void setAttachUrl(String attachUrl) {
		this.attachUrl = attachUrl;
	}

	public String getSequenceNumber() {
		return this.sequenceNumber;
	}

	public void setSequenceNumber(String sequenceNumber) {
		this.sequenceNumber = sequenceNumber;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getCommunicateStatus() {
		return this.communicateStatus;
	}

	public void setCommunicateStatus(String communicateStatus) {
		this.communicateStatus = communicateStatus;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getConcernNumber() {
		return this.concernNumber;
	}

	public void setConcernNumber(Integer concernNumber) {
		this.concernNumber = concernNumber;
	}

	public Integer getScanNumber() {
		return this.scanNumber;
	}

	public void setScanNumber(Integer scanNumber) {
		this.scanNumber = scanNumber;
	}

	public String getSeqNum() {
		return this.seqNum;
	}

	public void setSeqNum(String seqNum) {
		this.seqNum = seqNum;
	}

	public String getRecommendFlag() {
		return this.recommendFlag;
	}

	public void setRecommendFlag(String recommendFlag) {
		this.recommendFlag = recommendFlag;
	}

	public String getLogoUrl() {
		return this.logoUrl;
	}

	public void setLogoUrl(String logoUrl) {
		this.logoUrl = logoUrl;
	}

	public Date getWhenCreate() {
		return this.whenCreate;
	}

	public void setWhenCreate(Date whenCreate) {
		this.whenCreate = whenCreate;
	}

	public String getWhoCreate() {
		return this.whoCreate;
	}

	public void setWhoCreate(String whoCreate) {
		this.whoCreate = whoCreate;
	}

	public Date getWhenLastUpdate() {
		return this.whenLastUpdate;
	}

	public void setWhenLastUpdate(Date whenLastUpdate) {
		this.whenLastUpdate = whenLastUpdate;
	}

	public String getWhoLastUpdate() {
		return this.whoLastUpdate;
	}

	public void setWhoLastUpdate(String whoLastUpdate) {
		this.whoLastUpdate = whoLastUpdate;
	}

	public String getRemoveFlag() {
		return this.removeFlag;
	}

	public void setRemoveFlag(String removeFlag) {
		this.removeFlag = removeFlag;
	}

	public Set<FundRequirementFollower> getFundRequirementFollowers() {
		return this.fundRequirementFollowers;
	}

	public void setFundRequirementFollowers(
			Set<FundRequirementFollower> fundRequirementFollowers) {
		this.fundRequirementFollowers = fundRequirementFollowers;
	}

}
