package com.deep.two.orm;

// Generated 2016-12-27 21:27:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * FundRequirementFollower generated by hbm2java
 */
public class FundRequirementFollower implements java.io.Serializable {

	private FundRequirementFollowerId id;
	private User user;
	private FundRequirement fundRequirement;
	private String followerType;
	private String content;
	private String communicateStatus;
	private String status;
	private String remark;
	private Date whenCreate;
	private String whoCreate;
	private Date whenLastUpdate;
	private String whoLastUpdate;
	private String removeFlag;

	public FundRequirementFollower() {
	}

	public FundRequirementFollower(FundRequirementFollowerId id, User user,
			FundRequirement fundRequirement) {
		this.id = id;
		this.user = user;
		this.fundRequirement = fundRequirement;
	}

	public FundRequirementFollower(FundRequirementFollowerId id, User user,
			FundRequirement fundRequirement, String followerType,
			String content, String communicateStatus, String status,
			String remark, Date whenCreate, String whoCreate,
			Date whenLastUpdate, String whoLastUpdate, String removeFlag) {
		this.id = id;
		this.user = user;
		this.fundRequirement = fundRequirement;
		this.followerType = followerType;
		this.content = content;
		this.communicateStatus = communicateStatus;
		this.status = status;
		this.remark = remark;
		this.whenCreate = whenCreate;
		this.whoCreate = whoCreate;
		this.whenLastUpdate = whenLastUpdate;
		this.whoLastUpdate = whoLastUpdate;
		this.removeFlag = removeFlag;
	}

	public FundRequirementFollowerId getId() {
		return this.id;
	}

	public void setId(FundRequirementFollowerId id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public FundRequirement getFundRequirement() {
		return this.fundRequirement;
	}

	public void setFundRequirement(FundRequirement fundRequirement) {
		this.fundRequirement = fundRequirement;
	}

	public String getFollowerType() {
		return this.followerType;
	}

	public void setFollowerType(String followerType) {
		this.followerType = followerType;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getCommunicateStatus() {
		return this.communicateStatus;
	}

	public void setCommunicateStatus(String communicateStatus) {
		this.communicateStatus = communicateStatus;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getWhenCreate() {
		return this.whenCreate;
	}

	public void setWhenCreate(Date whenCreate) {
		this.whenCreate = whenCreate;
	}

	public String getWhoCreate() {
		return this.whoCreate;
	}

	public void setWhoCreate(String whoCreate) {
		this.whoCreate = whoCreate;
	}

	public Date getWhenLastUpdate() {
		return this.whenLastUpdate;
	}

	public void setWhenLastUpdate(Date whenLastUpdate) {
		this.whenLastUpdate = whenLastUpdate;
	}

	public String getWhoLastUpdate() {
		return this.whoLastUpdate;
	}

	public void setWhoLastUpdate(String whoLastUpdate) {
		this.whoLastUpdate = whoLastUpdate;
	}

	public String getRemoveFlag() {
		return this.removeFlag;
	}

	public void setRemoveFlag(String removeFlag) {
		this.removeFlag = removeFlag;
	}

}
