package com.deep.two.orm;

// Generated 2016-12-27 21:27:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InvestorUser generated by hbm2java
 */
public class InvestorUser implements java.io.Serializable {

	private String id;
	private User user;
	private String type;
	private String logoUrl;
	private String name;
	private String province;
	private String city;
	private String county;
	private Integer scale;
	private String address;
	private String introduction;
	private String contactName;
	private String contactTel;
	private String contactEmail;
	private String contactTitle;
	private String investDomain;
	private String investAmount;
	private String investPhase;
	private String investArea;
	private String investType;
	private String investExperience;
	private String investOutline;
	private String fundType;
	private String attachUrl;
	private String recommendFlag;
	private String seqNum;
	private String status;
	private String communicateStatus;
	private Date whenCreate;
	private String whoCreate;
	private Date whenLastUpdate;
	private String whoLastUpdate;
	private String removeFlag;
	private String attachName;
	private Set<InvestorFollower> investorFollowers = new HashSet<InvestorFollower>(
			0);

	public InvestorUser() {
	}

	public InvestorUser(String id, User user) {
		this.id = id;
		this.user = user;
	}

	public InvestorUser(String id, User user, String type, String logoUrl,
			String name, String province, String city, String county,
			Integer scale, String address, String introduction,
			String contactName, String contactTel, String contactEmail,
			String contactTitle, String investDomain, String investAmount,
			String investPhase, String investArea, String investType,
			String investExperience, String investOutline, String fundType,
			String attachUrl, String recommendFlag, String seqNum,
			String status, String communicateStatus, Date whenCreate,
			String whoCreate, Date whenLastUpdate, String whoLastUpdate,
			String removeFlag, String attachName,
			Set<InvestorFollower> investorFollowers) {
		this.id = id;
		this.user = user;
		this.type = type;
		this.logoUrl = logoUrl;
		this.name = name;
		this.province = province;
		this.city = city;
		this.county = county;
		this.scale = scale;
		this.address = address;
		this.introduction = introduction;
		this.contactName = contactName;
		this.contactTel = contactTel;
		this.contactEmail = contactEmail;
		this.contactTitle = contactTitle;
		this.investDomain = investDomain;
		this.investAmount = investAmount;
		this.investPhase = investPhase;
		this.investArea = investArea;
		this.investType = investType;
		this.investExperience = investExperience;
		this.investOutline = investOutline;
		this.fundType = fundType;
		this.attachUrl = attachUrl;
		this.recommendFlag = recommendFlag;
		this.seqNum = seqNum;
		this.status = status;
		this.communicateStatus = communicateStatus;
		this.whenCreate = whenCreate;
		this.whoCreate = whoCreate;
		this.whenLastUpdate = whenLastUpdate;
		this.whoLastUpdate = whoLastUpdate;
		this.removeFlag = removeFlag;
		this.attachName = attachName;
		this.investorFollowers = investorFollowers;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getLogoUrl() {
		return this.logoUrl;
	}

	public void setLogoUrl(String logoUrl) {
		this.logoUrl = logoUrl;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	public Integer getScale() {
		return this.scale;
	}

	public void setScale(Integer scale) {
		this.scale = scale;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	public String getContactTel() {
		return this.contactTel;
	}

	public void setContactTel(String contactTel) {
		this.contactTel = contactTel;
	}

	public String getContactEmail() {
		return this.contactEmail;
	}

	public void setContactEmail(String contactEmail) {
		this.contactEmail = contactEmail;
	}

	public String getContactTitle() {
		return this.contactTitle;
	}

	public void setContactTitle(String contactTitle) {
		this.contactTitle = contactTitle;
	}

	public String getInvestDomain() {
		return this.investDomain;
	}

	public void setInvestDomain(String investDomain) {
		this.investDomain = investDomain;
	}

	public String getInvestAmount() {
		return this.investAmount;
	}

	public void setInvestAmount(String investAmount) {
		this.investAmount = investAmount;
	}

	public String getInvestPhase() {
		return this.investPhase;
	}

	public void setInvestPhase(String investPhase) {
		this.investPhase = investPhase;
	}

	public String getInvestArea() {
		return this.investArea;
	}

	public void setInvestArea(String investArea) {
		this.investArea = investArea;
	}

	public String getInvestType() {
		return this.investType;
	}

	public void setInvestType(String investType) {
		this.investType = investType;
	}

	public String getInvestExperience() {
		return this.investExperience;
	}

	public void setInvestExperience(String investExperience) {
		this.investExperience = investExperience;
	}

	public String getInvestOutline() {
		return this.investOutline;
	}

	public void setInvestOutline(String investOutline) {
		this.investOutline = investOutline;
	}

	public String getFundType() {
		return this.fundType;
	}

	public void setFundType(String fundType) {
		this.fundType = fundType;
	}

	public String getAttachUrl() {
		return this.attachUrl;
	}

	public void setAttachUrl(String attachUrl) {
		this.attachUrl = attachUrl;
	}

	public String getRecommendFlag() {
		return this.recommendFlag;
	}

	public void setRecommendFlag(String recommendFlag) {
		this.recommendFlag = recommendFlag;
	}

	public String getSeqNum() {
		return this.seqNum;
	}

	public void setSeqNum(String seqNum) {
		this.seqNum = seqNum;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getCommunicateStatus() {
		return this.communicateStatus;
	}

	public void setCommunicateStatus(String communicateStatus) {
		this.communicateStatus = communicateStatus;
	}

	public Date getWhenCreate() {
		return this.whenCreate;
	}

	public void setWhenCreate(Date whenCreate) {
		this.whenCreate = whenCreate;
	}

	public String getWhoCreate() {
		return this.whoCreate;
	}

	public void setWhoCreate(String whoCreate) {
		this.whoCreate = whoCreate;
	}

	public Date getWhenLastUpdate() {
		return this.whenLastUpdate;
	}

	public void setWhenLastUpdate(Date whenLastUpdate) {
		this.whenLastUpdate = whenLastUpdate;
	}

	public String getWhoLastUpdate() {
		return this.whoLastUpdate;
	}

	public void setWhoLastUpdate(String whoLastUpdate) {
		this.whoLastUpdate = whoLastUpdate;
	}

	public String getRemoveFlag() {
		return this.removeFlag;
	}

	public void setRemoveFlag(String removeFlag) {
		this.removeFlag = removeFlag;
	}

	public String getAttachName() {
		return this.attachName;
	}
	public void setAttachName(String attachName) {
		this.attachName = attachName;
	}
	public Set<InvestorFollower> getInvestorFollowers() {
		return this.investorFollowers;
	}

	public void setInvestorFollowers(Set<InvestorFollower> investorFollowers) {
		this.investorFollowers = investorFollowers;
	}

}
