package com.deep.two.orm;

// Generated 2016-12-27 21:27:57 by Hibernate Tools 3.4.0.CR1

/**
 * InvestorFollowerId generated by hbm2java
 */
public class InvestorFollowerId implements java.io.Serializable {

	private String userId;
	private String investorId;
	private String relationType;

	public InvestorFollowerId() {
	}

	public InvestorFollowerId(String userId, String investorId,
			String relationType) {
		this.userId = userId;
		this.investorId = investorId;
		this.relationType = relationType;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getInvestorId() {
		return this.investorId;
	}

	public void setInvestorId(String investorId) {
		this.investorId = investorId;
	}

	public String getRelationType() {
		return this.relationType;
	}

	public void setRelationType(String relationType) {
		this.relationType = relationType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InvestorFollowerId))
			return false;
		InvestorFollowerId castOther = (InvestorFollowerId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this
				.getUserId() != null && castOther.getUserId() != null && this
				.getUserId().equals(castOther.getUserId())))
				&& ((this.getInvestorId() == castOther.getInvestorId()) || (this
						.getInvestorId() != null
						&& castOther.getInvestorId() != null && this
						.getInvestorId().equals(castOther.getInvestorId())))
				&& ((this.getRelationType() == castOther.getRelationType()) || (this
						.getRelationType() != null
						&& castOther.getRelationType() != null && this
						.getRelationType().equals(castOther.getRelationType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37
				* result
				+ (getInvestorId() == null ? 0 : this.getInvestorId()
						.hashCode());
		result = 37
				* result
				+ (getRelationType() == null ? 0 : this.getRelationType()
						.hashCode());
		return result;
	}

}
