package com.deep.two.orm;

// Generated 2016-12-27 21:27:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ResearchUser generated by hbm2java
 */
public class ResearchUser implements java.io.Serializable {

	private String id;
	private User user;
	private String type;
	private String uniName;
	private String uniDepartment;
	private String uniProvince;
	private String uniCity;
	private String uniLevel;
	private String uniNature;
	private Integer uniProject211;
	private Integer uniProject985;
	private Integer uniNationalPriority;
	private String orgName;
	private String orgProvince;
	private String orgCity;
	private String orgCounty;
	private String address;
	private String introduction;
	private String status;
	private String communicateStatus;
	private Date whenCreate;
	private String whoCreate;
	private Date whenLastUpdate;
	private String whoLastUpdate;
	private String removeFlag;
	private Set<ResearchGroup> researchGroups = new HashSet<ResearchGroup>(0);

	public ResearchUser() {
	}

	public ResearchUser(String id, User user) {
		this.id = id;
		this.user = user;
	}

	public ResearchUser(String id, User user, String type, String uniName,
			String uniDepartment, String uniProvince, String uniCity,
			String uniLevel, String uniNature, Integer uniProject211,
			Integer uniProject985, Integer uniNationalPriority, String orgName,
			String orgProvince, String orgCity, String orgCounty,
			String address, String introduction, String status,
			String communicateStatus, Date whenCreate, String whoCreate,
			Date whenLastUpdate, String whoLastUpdate, String removeFlag,
			Set<ResearchGroup> researchGroups) {
		this.id = id;
		this.user = user;
		this.type = type;
		this.uniName = uniName;
		this.uniDepartment = uniDepartment;
		this.uniProvince = uniProvince;
		this.uniCity = uniCity;
		this.uniLevel = uniLevel;
		this.uniNature = uniNature;
		this.uniProject211 = uniProject211;
		this.uniProject985 = uniProject985;
		this.uniNationalPriority = uniNationalPriority;
		this.orgName = orgName;
		this.orgProvince = orgProvince;
		this.orgCity = orgCity;
		this.orgCounty = orgCounty;
		this.address = address;
		this.introduction = introduction;
		this.status = status;
		this.communicateStatus = communicateStatus;
		this.whenCreate = whenCreate;
		this.whoCreate = whoCreate;
		this.whenLastUpdate = whenLastUpdate;
		this.whoLastUpdate = whoLastUpdate;
		this.removeFlag = removeFlag;
		this.researchGroups = researchGroups;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getUniName() {
		return this.uniName;
	}

	public void setUniName(String uniName) {
		this.uniName = uniName;
	}

	public String getUniDepartment() {
		return this.uniDepartment;
	}

	public void setUniDepartment(String uniDepartment) {
		this.uniDepartment = uniDepartment;
	}

	public String getUniProvince() {
		return this.uniProvince;
	}

	public void setUniProvince(String uniProvince) {
		this.uniProvince = uniProvince;
	}

	public String getUniCity() {
		return this.uniCity;
	}

	public void setUniCity(String uniCity) {
		this.uniCity = uniCity;
	}

	public String getUniLevel() {
		return this.uniLevel;
	}

	public void setUniLevel(String uniLevel) {
		this.uniLevel = uniLevel;
	}

	public String getUniNature() {
		return this.uniNature;
	}

	public void setUniNature(String uniNature) {
		this.uniNature = uniNature;
	}

	public Integer getUniProject211() {
		return this.uniProject211;
	}

	public void setUniProject211(Integer uniProject211) {
		this.uniProject211 = uniProject211;
	}

	public Integer getUniProject985() {
		return this.uniProject985;
	}

	public void setUniProject985(Integer uniProject985) {
		this.uniProject985 = uniProject985;
	}

	public Integer getUniNationalPriority() {
		return this.uniNationalPriority;
	}

	public void setUniNationalPriority(Integer uniNationalPriority) {
		this.uniNationalPriority = uniNationalPriority;
	}

	public String getOrgName() {
		return this.orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public String getOrgProvince() {
		return this.orgProvince;
	}

	public void setOrgProvince(String orgProvince) {
		this.orgProvince = orgProvince;
	}

	public String getOrgCity() {
		return this.orgCity;
	}

	public void setOrgCity(String orgCity) {
		this.orgCity = orgCity;
	}

	public String getOrgCounty() {
		return this.orgCounty;
	}

	public void setOrgCounty(String orgCounty) {
		this.orgCounty = orgCounty;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getCommunicateStatus() {
		return this.communicateStatus;
	}

	public void setCommunicateStatus(String communicateStatus) {
		this.communicateStatus = communicateStatus;
	}

	public Date getWhenCreate() {
		return this.whenCreate;
	}

	public void setWhenCreate(Date whenCreate) {
		this.whenCreate = whenCreate;
	}

	public String getWhoCreate() {
		return this.whoCreate;
	}

	public void setWhoCreate(String whoCreate) {
		this.whoCreate = whoCreate;
	}

	public Date getWhenLastUpdate() {
		return this.whenLastUpdate;
	}

	public void setWhenLastUpdate(Date whenLastUpdate) {
		this.whenLastUpdate = whenLastUpdate;
	}

	public String getWhoLastUpdate() {
		return this.whoLastUpdate;
	}

	public void setWhoLastUpdate(String whoLastUpdate) {
		this.whoLastUpdate = whoLastUpdate;
	}

	public String getRemoveFlag() {
		return this.removeFlag;
	}

	public void setRemoveFlag(String removeFlag) {
		this.removeFlag = removeFlag;
	}

	public Set<ResearchGroup> getResearchGroups() {
		return this.researchGroups;
	}

	public void setResearchGroups(Set<ResearchGroup> researchGroups) {
		this.researchGroups = researchGroups;
	}

}
