package com.deep.two.orm;

// Generated 2016-12-27 21:27:57 by Hibernate Tools 3.4.0.CR1

/**
 * ResearchGroupFollowerId generated by hbm2java
 */
public class ResearchGroupFollowerId implements java.io.Serializable {

	private String userId;
	private String researchId;
	private String relationType;

	public ResearchGroupFollowerId() {
	}

	public ResearchGroupFollowerId(String userId, String researchId,
			String relationType) {
		this.userId = userId;
		this.researchId = researchId;
		this.relationType = relationType;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getResearchId() {
		return this.researchId;
	}

	public void setResearchId(String researchId) {
		this.researchId = researchId;
	}

	public String getRelationType() {
		return this.relationType;
	}

	public void setRelationType(String relationType) {
		this.relationType = relationType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResearchGroupFollowerId))
			return false;
		ResearchGroupFollowerId castOther = (ResearchGroupFollowerId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this
				.getUserId() != null && castOther.getUserId() != null && this
				.getUserId().equals(castOther.getUserId())))
				&& ((this.getResearchId() == castOther.getResearchId()) || (this
						.getResearchId() != null
						&& castOther.getResearchId() != null && this
						.getResearchId().equals(castOther.getResearchId())))
				&& ((this.getRelationType() == castOther.getRelationType()) || (this
						.getRelationType() != null
						&& castOther.getRelationType() != null && this
						.getRelationType().equals(castOther.getRelationType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37
				* result
				+ (getResearchId() == null ? 0 : this.getResearchId()
						.hashCode());
		result = 37
				* result
				+ (getRelationType() == null ? 0 : this.getRelationType()
						.hashCode());
		return result;
	}

}
