package com.deep.two.orm;

// Generated 2016-12-27 21:27:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private String id;
	private String roleName;
	private String roleDesc;
	private Set<UserRole> userRoles = new HashSet<UserRole>(0);
	private Set<RoleResource> roleResources = new HashSet<RoleResource>(0);

	public Role() {
	}

	public Role(String id) {
		this.id = id;
	}

	public Role(String id, String roleName, String roleDesc,
			Set<UserRole> userRoles, Set<RoleResource> roleResources) {
		this.id = id;
		this.roleName = roleName;
		this.roleDesc = roleDesc;
		this.userRoles = userRoles;
		this.roleResources = roleResources;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getRoleDesc() {
		return this.roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

	public Set<UserRole> getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set<UserRole> userRoles) {
		this.userRoles = userRoles;
	}

	public Set<RoleResource> getRoleResources() {
		return this.roleResources;
	}

	public void setRoleResources(Set<RoleResource> roleResources) {
		this.roleResources = roleResources;
	}

}
