package com.deep.two.orm;

// Generated 2016-12-27 21:27:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TechRequirementFollower generated by hbm2java
 */
public class TechRequirementFollower implements java.io.Serializable {

	private TechRequirementFollowerId id;
	private User user;
	private TechRequirement techRequirement;
	private String followerType;
	private String content;
	private String status;
	private String communicateStatus;
	private String remark;
	private Date whenCreate;
	private String whoCreate;
	private Date whenLastUpdate;
	private String whoLastUpdate;
	private String removeFlag;

	public TechRequirementFollower() {
	}

	public TechRequirementFollower(TechRequirementFollowerId id, User user,
			TechRequirement techRequirement) {
		this.id = id;
		this.user = user;
		this.techRequirement = techRequirement;
	}

	public TechRequirementFollower(TechRequirementFollowerId id, User user,
			TechRequirement techRequirement, String followerType,
			String content, String status, String communicateStatus,
			String remark, Date whenCreate, String whoCreate,
			Date whenLastUpdate, String whoLastUpdate, String removeFlag) {
		this.id = id;
		this.user = user;
		this.techRequirement = techRequirement;
		this.followerType = followerType;
		this.content = content;
		this.status = status;
		this.communicateStatus = communicateStatus;
		this.remark = remark;
		this.whenCreate = whenCreate;
		this.whoCreate = whoCreate;
		this.whenLastUpdate = whenLastUpdate;
		this.whoLastUpdate = whoLastUpdate;
		this.removeFlag = removeFlag;
	}

	public TechRequirementFollowerId getId() {
		return this.id;
	}

	public void setId(TechRequirementFollowerId id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public TechRequirement getTechRequirement() {
		return this.techRequirement;
	}

	public void setTechRequirement(TechRequirement techRequirement) {
		this.techRequirement = techRequirement;
	}

	public String getFollowerType() {
		return this.followerType;
	}

	public void setFollowerType(String followerType) {
		this.followerType = followerType;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getCommunicateStatus() {
		return this.communicateStatus;
	}

	public void setCommunicateStatus(String communicateStatus) {
		this.communicateStatus = communicateStatus;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getWhenCreate() {
		return this.whenCreate;
	}

	public void setWhenCreate(Date whenCreate) {
		this.whenCreate = whenCreate;
	}

	public String getWhoCreate() {
		return this.whoCreate;
	}

	public void setWhoCreate(String whoCreate) {
		this.whoCreate = whoCreate;
	}

	public Date getWhenLastUpdate() {
		return this.whenLastUpdate;
	}

	public void setWhenLastUpdate(Date whenLastUpdate) {
		this.whenLastUpdate = whenLastUpdate;
	}

	public String getWhoLastUpdate() {
		return this.whoLastUpdate;
	}

	public void setWhoLastUpdate(String whoLastUpdate) {
		this.whoLastUpdate = whoLastUpdate;
	}

	public String getRemoveFlag() {
		return this.removeFlag;
	}

	public void setRemoveFlag(String removeFlag) {
		this.removeFlag = removeFlag;
	}

}
