package com.deep.two.orm;

// Generated 2016-12-27 21:27:57 by Hibernate Tools 3.4.0.CR1

/**
 * UserRole generated by hbm2java
 */
public class UserRole implements java.io.Serializable {

	private UserRoleId id;
	private User user;
	private Role role;
	private String enabled;

	public UserRole() {
	}

	public UserRole(UserRoleId id, User user, Role role) {
		this.id = id;
		this.user = user;
		this.role = role;
	}

	public UserRole(UserRoleId id, User user, Role role, String enabled) {
		this.id = id;
		this.user = user;
		this.role = role;
		this.enabled = enabled;
	}

	public UserRoleId getId() {
		return this.id;
	}

	public void setId(UserRoleId id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

}
