package com.deep.two.orm;

// Generated 2016-12-27 21:27:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String id;
	private String username;
	private String password;
	private String email;
	private String telno;
	private String userType;
	private Date whenCreate;
	private Date whenLastUpdate;
	private Date whenLastLogin;
	private String status;
	private String communicateStatus;
	private String remark;
	private String whoCreate;
	private String whoLastUpdate;
	private String removeFlag;
	private Set<AchievementFollower> achievementFollowers = new HashSet<AchievementFollower>(
			0);
	private Set<CompanyUser> companyUsers = new HashSet<CompanyUser>(0);
	private Set<TechRequirementFollower> techRequirementFollowers = new HashSet<TechRequirementFollower>(
			0);
	private Set<FundRequirementFollower> fundRequirementFollowers = new HashSet<FundRequirementFollower>(
			0);
	private Set<ResearchUser> researchUsers = new HashSet<ResearchUser>(0);
	private Set<ResearchGroupFollower> researchGroupFollowers = new HashSet<ResearchGroupFollower>(
			0);
	private Set<UserRole> userRoles = new HashSet<UserRole>(0);
	private Set<InvestorUser> investorUsers = new HashSet<InvestorUser>(0);
	private Set<InvestorFollower> investorFollowers = new HashSet<InvestorFollower>(
			0);

	public User() {
	}

	public User(String id) {
		this.id = id;
	}

	public User(String id, String username, String password, String email,
			String telno, String userType, Date whenCreate,
			Date whenLastUpdate, Date whenLastLogin, String status,
			String communicateStatus, String remark, String whoCreate,
			String whoLastUpdate, String removeFlag,
			Set<AchievementFollower> achievementFollowers,
			Set<CompanyUser> companyUsers,
			Set<TechRequirementFollower> techRequirementFollowers,
			Set<FundRequirementFollower> fundRequirementFollowers,
			Set<ResearchUser> researchUsers,
			Set<ResearchGroupFollower> researchGroupFollowers,
			Set<UserRole> userRoles, Set<InvestorUser> investorUsers,
			Set<InvestorFollower> investorFollowers) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.email = email;
		this.telno = telno;
		this.userType = userType;
		this.whenCreate = whenCreate;
		this.whenLastUpdate = whenLastUpdate;
		this.whenLastLogin = whenLastLogin;
		this.status = status;
		this.communicateStatus = communicateStatus;
		this.remark = remark;
		this.whoCreate = whoCreate;
		this.whoLastUpdate = whoLastUpdate;
		this.removeFlag = removeFlag;
		this.achievementFollowers = achievementFollowers;
		this.companyUsers = companyUsers;
		this.techRequirementFollowers = techRequirementFollowers;
		this.fundRequirementFollowers = fundRequirementFollowers;
		this.researchUsers = researchUsers;
		this.researchGroupFollowers = researchGroupFollowers;
		this.userRoles = userRoles;
		this.investorUsers = investorUsers;
		this.investorFollowers = investorFollowers;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelno() {
		return this.telno;
	}

	public void setTelno(String telno) {
		this.telno = telno;
	}

	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public Date getWhenCreate() {
		return this.whenCreate;
	}

	public void setWhenCreate(Date whenCreate) {
		this.whenCreate = whenCreate;
	}

	public Date getWhenLastUpdate() {
		return this.whenLastUpdate;
	}

	public void setWhenLastUpdate(Date whenLastUpdate) {
		this.whenLastUpdate = whenLastUpdate;
	}

	public Date getWhenLastLogin() {
		return this.whenLastLogin;
	}

	public void setWhenLastLogin(Date whenLastLogin) {
		this.whenLastLogin = whenLastLogin;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getCommunicateStatus() {
		return this.communicateStatus;
	}

	public void setCommunicateStatus(String communicateStatus) {
		this.communicateStatus = communicateStatus;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getWhoCreate() {
		return this.whoCreate;
	}

	public void setWhoCreate(String whoCreate) {
		this.whoCreate = whoCreate;
	}

	public String getWhoLastUpdate() {
		return this.whoLastUpdate;
	}

	public void setWhoLastUpdate(String whoLastUpdate) {
		this.whoLastUpdate = whoLastUpdate;
	}

	public String getRemoveFlag() {
		return this.removeFlag;
	}

	public void setRemoveFlag(String removeFlag) {
		this.removeFlag = removeFlag;
	}

	public Set<AchievementFollower> getAchievementFollowers() {
		return this.achievementFollowers;
	}

	public void setAchievementFollowers(
			Set<AchievementFollower> achievementFollowers) {
		this.achievementFollowers = achievementFollowers;
	}

	public Set<CompanyUser> getCompanyUsers() {
		return this.companyUsers;
	}

	public void setCompanyUsers(Set<CompanyUser> companyUsers) {
		this.companyUsers = companyUsers;
	}

	public Set<TechRequirementFollower> getTechRequirementFollowers() {
		return this.techRequirementFollowers;
	}

	public void setTechRequirementFollowers(
			Set<TechRequirementFollower> techRequirementFollowers) {
		this.techRequirementFollowers = techRequirementFollowers;
	}

	public Set<FundRequirementFollower> getFundRequirementFollowers() {
		return this.fundRequirementFollowers;
	}

	public void setFundRequirementFollowers(
			Set<FundRequirementFollower> fundRequirementFollowers) {
		this.fundRequirementFollowers = fundRequirementFollowers;
	}

	public Set<ResearchUser> getResearchUsers() {
		return this.researchUsers;
	}

	public void setResearchUsers(Set<ResearchUser> researchUsers) {
		this.researchUsers = researchUsers;
	}

	public Set<ResearchGroupFollower> getResearchGroupFollowers() {
		return this.researchGroupFollowers;
	}

	public void setResearchGroupFollowers(
			Set<ResearchGroupFollower> researchGroupFollowers) {
		this.researchGroupFollowers = researchGroupFollowers;
	}

	public Set<UserRole> getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set<UserRole> userRoles) {
		this.userRoles = userRoles;
	}

	public Set<InvestorUser> getInvestorUsers() {
		return this.investorUsers;
	}

	public void setInvestorUsers(Set<InvestorUser> investorUsers) {
		this.investorUsers = investorUsers;
	}

	public Set<InvestorFollower> getInvestorFollowers() {
		return this.investorFollowers;
	}

	public void setInvestorFollowers(Set<InvestorFollower> investorFollowers) {
		this.investorFollowers = investorFollowers;
	}

}
